### ISSUE TITLE
Failed to load schematic

### ISSUE THREAD

**Issue by iCentricks** [maruohon/litematica#102]
Hey, I have been using litematica for a while now and ever since the 1.15.2 update I can't load any schematics at all, it just says failed to load schematic for every one of them. I tried re-installing Minecraft and everything else, idk if anyone else is having this issue or if its just me but yeah idk, can't load any, not old ones not new ones either. I can mess with the settings and stuff though and all the menus come up and nothing seems to be giving any errors anywhere other than the fact I can't actually load any schematics. 

Any help is appreciated, thanks.

**Comment by vacla** [comment]
Is it a litematic?

**Comment by maruohon** [comment]
The 1.15.2 build are currently not based on the private schematic-import branch I have, which the 1.14.4 and 1.15.0 and 1.15.1 builds are based on. Which means that the current 1.15.2 build indeed can not load any of the old MCEdit/Schematica schematics.

Basically it's currently a bit annoying and more work if I need to keep fiddling around with the branches when I need to update to new Minecraft versions and then include that schematic import support to it separately since that code is not in the main branch, so I didn't do it with the current 1.15.2 build. I probably need to include it back again because otherwise it's going to be annoying and more work for the users to load old schematics until I get the final proper import support merged somewhere down the line...

**Comment by iCentricks** [comment]
So what do you think I should do in the mean time? Is there a way for me to manually convert schematics to litematics? some type of converter?

**Comment by iCentricks** [comment]
> Is it a litematic?

No, it is not, I was just letting the mod convert it itself because up until 1.15.2 I had no issues just downloading any schematic and opening it even if it was a .schematic

**Comment by SunSerega** [comment]
> So what do you think I should do in the mean time?

Load your schematic in older version and paste in temp world.
That load this world in 1.15.2 and create new `.litematic` from it.

This is an always-working way to transfer schematics though versions.

**Comment by maruohon** [comment]
I'm going to make a new build with the import support added back in, but in the mean time (so until I get that done in like an hour or two or whatever), you could import the schematic(s) you want to use in the 1.14.4 or 1.15.1 version using the Schematic Manager GUI -> Import and thus saving them in the Litematica format, which you can then load in the 1.15.2 version.

**Comment by maruohon** [comment]
Okay there is now a new 1.15.2 build with the old schematic import support restored.
https://masa.dy.fi/mcmods/client_mods/?mcver=1.15.2

**Comment by iCentricks** [comment]
> Okay there is now a new 1.15.2 build with the old schematic import support restored.
> https://masa.dy.fi/mcmods/client_mods/?mcver=1.15.2

Ok, i'll check it out soon, thanks for the fast replies. Appreciate it, also thanks for the tip.
