### ISSUE TITLE
"Pick last" crashes

### ISSUE THREAD

**Issue by SunSerega** [maruohon/litematica#13]
[crash-2019-01-18_11.56.28-client.txt](https://github.com/maruohon/litematica/files/2772433/crash-2019-01-18_11.56.28-client.txt)
[crash-2019-01-18_11.50.37-client.txt](https://github.com/maruohon/litematica/files/2772434/crash-2019-01-18_11.50.37-client.txt)

[config.zip](https://github.com/maruohon/litematica/files/2772438/config.zip)

Pressing Alt+MMB (which is pick last for me) crashes game.

It crashes stably when you have lamp, redstone block behind it, and then just stone wall. And both lamp and redstone block was in my inventory.

**Comment by maruohon** [comment]
This was fixed by 3d30b94b5c in the 1.12 development code, so the fix will be in the next 1.13.2 build too after I merge in the 1.12 branch again. There are still a few things I'd like to implement for the next version. But maybe I should make a new release before those anyway because there are a few crash fixes pending... The main issue is that it's still possible that one of the planned changes/improvements might still need malilib changes, and I'd rather not make two incompatible releases in quick succession.

**Comment by maruohon** [comment]
This is fixed in the latest builds.
