### ISSUE TITLE
Litematica blocks change their rotation all the time

### ISSUE THREAD

**Issue by SunSerega** [maruohon/litematica#14]
https://youtu.be/w_FlcZfXPno

Block rotations must be based on position in the world:
https://youtu.be/6__hO4cc1pA?t=440
So they must not be always rotated randomly.

Also, if block is already right one - there is no need to redraw it, every time something happens near it.

**Comment by SunSerega** [comment]
btw, RMB also updates everything, so when you do something like bridging - it flickers indefinitely, dropping fps 55->40.

**Comment by maruohon** [comment]
This was a bug in the 1.13.2 port, and was already fixed in a7f95e0749c0 and the fix will thus be in the next build.

The RMB issue is how vanilla works, it sends a couple of block change packets even for right clicks. I guess I could check if the synced block states actually were different before requesting a redraw.

**Comment by SunSerega** [comment]
> I guess I could check if the synced block states actually were different before requesting a redraw.

Yes, thats what i meant. It should probably improve performance. Without it fps would probably still drop 55 -> 40, even if nothing changed visually.

**Comment by maruohon** [comment]
This should be fixed in the latest builds.
