### ISSUE TITLE
How do you convert a schematic into commands

### ISSUE THREAD

**Issue by AppleGUY2812** [maruohon/litematica#143]

**Comment by maruohon** [comment]
I assume you mean how to paste it using vanilla `/setblock` commands? You just switch to the "Paste schematic in world" mode and the while holding the "tool" (stick) use the `executeOperation` hotkey. Depending on the server setting you may need to lower the commands per tick value and/or increase the interval between commands in the Generic configs (search for `paste`).

And as for other usage questions or help, you might want to use either the CurseForge comments, or ask on the SciCraft Discord server (https://discord.gg/scicraft) on the #masas-mods channel instead of here in the issue tracker.
