### ISSUE TITLE
Could not understandhow to load

### ISSUE THREAD

**Issue by Giuseh** [maruohon/litematica#151]
Hi, i was trying to load the schematics into my server with worldedit, beacuse if i try to place the blocks with the mod it tells me i'm going out of the world bounds, so how can i load schematic into my server ?
(I'm using 1.15.2 version)

**Comment by maruohon** [comment]
I actually uploaded a version with a fix for the "outside of world bounds" issue just yesterday, here: https://masa.dy.fi/mcmods/litematica/litematica-fabric-1.15.2-0.0.0-dev.20200414.222440.jar since someone else was having the same issue.

Currently there is no other way (in the 1.13.2+ versions of the mod) to convert Litematica schematics to World Edit schematics than to paste the Litematica schematic into a temporary world and save it with World Edit. In the 1.12.2 version there is already direct conversion/saving support for Sponge schematics too, but currently you can't convert between 1.12 <-> 1.13+ schematics yet, so it's not possible to use the 1.12.2 version to convert a 1.15.2 schematic either...

**Comment by Giuseh** [comment]
Ok thanks 😄 👍
