### ISSUE TITLE
Crash on Launch (Self Fix?)

### ISSUE THREAD

**Issue by TheGreatNaj** [maruohon/litematica#161]
I fixed my own problem at this point but I thought it might be useful to bring it to the attention of the dev for people who don't do as much digging.
As far as I could tell I had downloaded and installed everything right but it was crashing when I tried to launch.
Looking at the crash log it said I was missing madlib which I wasnt, but it needed specifically 0.10.0-dev.**19**. Looking at madlibs files they all says dev.20 for 1.15.2 but downloading the second to last latest 1.15.2 version (1.15.2-0.10.0-dev.20+arne.6) that one worked.

**Comment by maruohon** [comment]
`>=0.10.0-dev.19` means that it requires version dev.19 or newer. However that requirement is indeed wrong, it should say dev.20, and I should have even bumbed the version to dev.21 recently when I did the rendering changes in both mods that break rendering if versions are mismatched over that change... So I might do a version bump release just to fix that.

**Comment by TheGreatNaj** [comment]
Well that was part of the problem, the one that wasn't working WAS newer. Originally I downloaded the latest version madlib had on curse and thats the one that didnt work. I had to go to the files and download a slightly older one.

**Comment by maruohon** [comment]
The latest *uploaded* file is for Forge, not for Fabric. This is indicated both in the mod file name, and as a mod loader tag on CurseForge.

However I'm getting issue reports and crash reports pretty much every day because people download the Forge version while they are on Fabric... So I might create a separate malilib project for Forge to try to avoid this issue. However I don't want to create separate projects for every mod loader for every mod... I wish CurseForge would just handle and categorize the different mod loaders better >_>
