### ISSUE TITLE
Can't open .Schem files

### ISSUE THREAD

**Issue by Wisplings** [maruohon/litematica#183]
**Describe the bug**
I cant open .schem files, which i made by using world edit.

**To Reproduce** (if not clear from the description already)
1.  Copy a build, by //pos 1 and //pos 2, and //copy it
2. //schematic save (name)
3. Scroll down to where the schematic is saved
4. try to open it while using litematica and it wont open

**Expected behavior** (if not clear from the description)
open it as usual

**Comment by vacla** [comment]
in 1.13.2+ it is not possible yet to open *.schem files

**Comment by Wisplings** [comment]
How could I make a schematic file that’s works for 1.15.2?

**Comment by vacla** [comment]
not yet, it will after the merge happen from 1.12.2 to later versions

**Comment by maruohon** [comment]
Where/how do you want to use the schematic? If you want to use it in Litematica, you can just save it with Litematica.

Otherwise describe what you want it for and what format does it need to be in. I've been working on schematic conversion support between MC versions recently, so it's to some extent possible to convert formats in my current development code, although it's still not finished so converting 1.13+ schematics between different formats doesn't work quite yet, all 1.13+ blocks would vanish currently because it still needs to convert to the 1.12.2 format for the format conversions.

**Comment by Wisplings** [comment]
How can i save it with litematica?

**Comment by SunSerega** [comment]
I believe @maruohon meant making actual `.litematica` file, using main litematica features (creating selection and pressing saving hotkey).

**Comment by maruohon** [comment]
Basically you make an area selection, and then you save that as a schematic.

Check out this text explanation of the basics of the mod:
https://old.reddit.com/r/Minecraft/comments/cqdmkk/anyone_can_help_me_how_do_i_make_schematics_with/exeug78/

Or maybe watch this tutorial:
https://www.youtube.com/watch?v=aMZSXAKZzpo

**Comment by Wisplings** [comment]
TYSM :D it worked!
