### ISSUE TITLE
Implementation for new schematics!

### ISSUE THREAD

**Issue by Kapsll** [maruohon/litematica#194]
Even if the mod is for version 1.15.2 the supported schematics are up to 1.12 (.schematic) and it would be nice to also implement the new versions (.schem) that cannot be used at the moment!

**Comment by SmylerMC** [comment]
The mod supports 1.12+ blocks with litematics.

**Comment by maruohon** [comment]
Support for Sponge schematics (`*.schem`) has been implemented in the main development version on 1.12.2 a few months back. More recently I've also been working on conversion support between Minecraft versions, but that is still incomplete and work in progress.

So basically the intention is that Litematica will support all of the 4 common formats, it's own `*.litematic* , the old MCEdit/Schematica format `*.schematic`, the vanilla Structure Block format `*.nbt` and the Sponge schematic format `*.schem`. And also I want it to support loading any of those from any Minecraft version.

That conversion support between Minecraft versions is what is the most complex and difficult part of this, especially since I also want it to work such that you can for example convert a Sponge schematic made in 1.15.2 into the Litematica format for 1.15.2, while being in 1.12.2 while doing it, which means that I can't load the schematic to memory fully/normally, since the new blocks added in 1.13+ would otherwise vanish if the conversion is done in the 1.12.2 version of the mod.
