### ISSUE TITLE
1.16 failed to load schematic

### ISSUE THREAD

**Issue by trydar** [maruohon/litematica#201]
am on 1.16.1 all the latest versions, wont load any schematic files from mc edit. =(

**Comment by maruohon** [comment]
Can you send me one such schematic? Old MCEdit schematics from 1.12 should load, but the Sponge schematic format (used for example by World Edit in 1.13+) is currently only supported in the 1.12.2 version of Litematica.

**Comment by trydar** [comment]
ok here you go.

[test schematic 1.zip](https://github.com/maruohon/litematica/files/4875331/test.schematic.1.zip)

its the same as ive used in the 1.15 versions but it just wont load any schematics period.

mod files im using:
litematica-fabric-1.16.1-0.0.0-dev.20200630.022912
malilib-fabric-1.16.1-0.10.0-dev.21+arne.1
fabric-api-0.14.1+build.372-1.16
modmenu-1.12.2+build.17

**Comment by maruohon** [comment]
Okay this happens because the wall properties changed in 1.16, and the state fixer is now throwing exceptions because of this. Here is a temporary version which allows the schematics to load, but any walls are just left unconnected. I need to update that code after taking a better look at how it works now in 1.16.

https://masa.dy.fi/mcmods/litematica/litematica-fabric-1.16.1-0.0.0-dev.20200706.012442.jar

**Comment by trydar** [comment]
ok I will give that a test and report back, thanks!

**Comment by trydar** [comment]
ok I performed a test and it works fine now, thank you kindly =)

**Comment by maruohon** [comment]
This should be properly fixed in the 2020-07-11 version.
