### ISSUE TITLE
Texture Glitch and Tearing

### ISSUE THREAD

**Issue by 9514854** [maruohon/litematica#222]
intermediary-fabric-loader-0.9.2+build.206-1.16.2
fabric-api-0.19.0+build.398-1.16
litematica-fabric-1.16.2-0.0.0-dev.20200824.031346
malilib-fabric-1.16.2-0.10.0-dev.21+arne.1

I also have Optifabric installed, and it didn't cause an issue in 1.16.1, but I figured I'd mention it because it has an effect on visuals.

My issue is that after loading up my schematic that I was using in 1.16.1 that worked just fine, it looked like it does in the attached image. I tried messing with some video settings and some of the settings in the litematica, but nothing changed. Not sure what's going on, figured i'd report it as a bug.
![2020-09-02_00 40 12](https://user-images.githubusercontent.com/20209318/91941023-bcdc2080-ecb5-11ea-94d0-654e717622d6.png)

**Comment by maruohon** [comment]
This type of mess is pretty much always caused by Optifine (assuming it's installed), as it changes the vertex format. For some reason this started happening again in 1.16.2, although it was supposed to be fixed since the changes I did in 1.15.2.

Basically you want to disable Render Regions in Optifine, and if that doesn't help, then also make sure that shaders are set to OFF. You may need to restart the game completely after changing the settings. If neither of those help, then I guess you can't use Optifine at all anymore with Litematica.

**Comment by 9514854** [comment]
It looks like the problem was optifine internal shaders. I had to turn them off and restart the game before things went back to normal. I actually can leave Render Regions on and litematica functions normally. I haven't tested it with other shaders, but optifine internal shaders are definitely a no-go.

**Comment by Chocohead** [comment]
From some casual testing, ensuring the vanilla block vertex format is used [here](https://github.com/maruohon/litematica/blob/fabric_1.16_snapshots_temp/src/main/java/fi/dy/masa/litematica/render/schematic/WorldRendererSchematic.java#L59) stops it from drawing the wacky underfilled buffer triangles. I would have said the two direct references in `ChunkRendererSchematicVbo` also need similar treatment, but it seems like the repo is a little behind what is on Curse as that already seems to? Either way it's not a perfect fix as the blue/red box frames seem to not render for whatever reason. It's my first look into what Litematica does for rendering so don't have any immediate suggestions why it would be the case.
