### ISSUE TITLE
Add auto build for survival

### ISSUE THREAD

**Issue by Madff386** [maruohon/litematica#261]
**Is your feature request related to a problem? Please describe.**
In survival after I’ve gathered all the materials for a build actually building it is sort of boring.

**Describe the solution you'd like**
Could you add a baritone like functionality where once the player has all the materials and some scaffolding blocks. They could press a hot key and then player would start moving and building the structure itself.

**Comment by maruohon** [comment]
There certainly won't be Baritone level auto-building in this mod. A survival printer (without automatic player movement) is planned. But I've also decided that that printer also won't be in Litematica directly, but instead in a separate extension mod. This is because lots of people don't like the idea of a printer and don't want to use it, and lots of servers also don't allow a printer, so keeping it in a separate extension mod is nicer and clearer in that regard.

There are also currently already both a 3rd party printer extension mod and a fork with a printer.
* extension: https://github.com/eatmyvenom/litematica-printer
* fork: https://github.com/aleksilassila/litematica-printer

**Comment by Madff386** [comment]
ok thanks
