### ISSUE TITLE
Can't open the menu

### ISSUE THREAD

**Issue by WateryLemon** [maruohon/litematica#299]
Hi, I mapped the M (open menu) to Ctrl + M, and now i can no longer open the menu. There are no conflicting key binds and i can't change it in the vanilla control setting of Minecraft
Please help
P.S I am on version 1.16.5

**Comment by maruohon** [comment]
My mod hotkeys are not in the vanilla controls menu, as they use the custom keybind system in malilib. If you didn't re-map the config menu hotkey yet, you can use that to open the config menu directly:  `M + C`. Otherwise if you have the Mod Menu mod installed, you can open the mod config menu via the config menu button there. Otherwise you can edit the config file manually at `.minecraft/config/litematica.json`, and look for `openConfigGui` and/or `openGuiMainMenu`.
