### ISSUE TITLE
Many question about use

### ISSUE THREAD

**Issue by Culvanen** [maruohon/litematica#3]
Hello,

Thank you first of all for your work on the mod.

I have some questions about how the mod works, the pastebin provided seems very obscure to me.

- I have a big schematics (170 * 71 * 69) when I place it I only have a blue square that appears, I do not know how to place it on the map correctly so that it appears in transparency.

Thanks

**Comment by Culvanen** [comment]
Hi, 

My first problem is solved, but i have a new problem:

My right click seems not working, how to reactivate ?

**Comment by maruohon** [comment]
In what context is it not working? Do you mean you can't even place blocks anymore elsewhere, or is some of the mod functionality related to right clicks/hotkeys containing right click not working?

**Comment by Cazitron** [comment]
How do you use the "easyPlaceActivation" or "easyPlaceToggle", if it is even implemented yet and I'm assuming it's just like the printer function from "Schematica" right?

**Comment by maruohon** [comment]
Easy Place is not the "full printer", it's more like a manual version of the printer. So with Easy Place you basically have to look at each of the schematic blocks and then right click to place that block. It then does an automatic pick block, and then places the block in the targeted position.

To use it, you toggle it on, and then either hold the activation key for it while right clicking on the schematic blocks, or if you set the activation key tot NONE, then it will work simply by right clicking (or whatever your use key is bound to) on the schematic blocks. Also note, that while you have the Easy Place mode enabled, you can't right click or use any other items, such as eating some food, so you'll have to toggle it off if you need to eat for example.

Also note that the Easy Place mode will currently only place the blocks in the correct orientation on a Carpet mod server with the help of the Accurate Placement protocol in the Carpet mod. (Carpet mod is a server-side jar mod mainly geared for technical vanilla players, and currently only exists for MC 1.12.0 and 1.13.1.) I will implement the correct rotation for the Easy Place mode for single player too at some point, but due to a certain change in vanilla 1.13, it's not really possible to properly implement it for all blocks on non-Carpet servers in 1.13 anymore (this only affects pistons, observers, droppers and dispensers though). Also the "full printer" (like Schematica has) will be added at some point.

If you want to easily duplicate/build stuff in creative mode in single player, then you can use the Paste Schematic in World mode to paste the entire schematic at once. To use that, switch to that mode [5/7], position the placement where you want it, and then hit the `executeOperation` hotkey to paste it into the world.
