### ISSUE TITLE
Can't place block

### ISSUE THREAD

**Issue by naveh21** [maruohon/litematica#324]
When I right click a block in the schematic, it doesn't place the block, it creates another next to it and I cant place the block.

**Comment by maruohon** [comment]
You are in the Schematic Rebuild mode then. That mode is meant for editing schematics, switch out of it to literally any other mode. Normally you would be in the Schematic Placement mode while building stuff (so that the tool will control the schematic placement positioning).

In retrospect I know that the tool mode name `Schematic Rebuild` is misleading/confusing, and it will be renamed to the `Schematic Edit` mode in future versions. The reasoning was that you can literally change and build stuff again within the schematic, to fix or change things in it.
