### ISSUE TITLE
Selection Bug?

### ISSUE THREAD

**Issue by Lee-1993** [maruohon/litematica#335]
Everytime I do m+s while trying to schematic something it keeps on adding extra sub-regions. I have tried everything I can think of to fix this, including redownloading the mods, getting rid of optifine ect. I've been using it for months and then suddenly it started doing this...
![2021-04-18_21 03 35](https://user-images.githubusercontent.com/82750850/115143296-cf129f80-a089-11eb-850f-74076d6d97fe.png)

**Comment by maruohon** [comment]
Did you change some of the hotkeys? By default `M + A` (Hotkeys -> `addSelectionBox`) adds new sub-regions, while `M + S` (Hotkeys -> `openGuiSelectionManager`) should open the Area Selection Browser menu.

It's quite rare that you would need to use either of those two keybinds. Usually it's quite acceptable clicking one extra time going through the main menu to the Area Selection Browser to start a new selection, and if you need to create more sub-regions then using the Area Editor menu (by default numpad multiply) is better than using the hotkey to create the, as you can then also name it properly immediately. I will probably remove the default hotkey to add sub-regions in future releases, if someone wants to use that hey can then just bind it again

And if you don't need/want more than one sub-region, then I'd suggest using the "Simple" area selection mode instead of the "Normal" mode. Then you also don't need to go and create the selection via the Area Selection Browser menu, as there is ever only one "global selection thing" in the Simple mode. You can switch the mode in the main menu or in the Area Editor menu.

**Comment by Lee-1993** [comment]
omg... you are a lifesaver lmao I can't believe it. 1. how did I miss that?! and 2. How did that even happen?! Thank you so much!
