### ISSUE TITLE
menu don't open

### ISSUE THREAD

**Issue by basil222** [maruohon/litematica#338]
when holding a stick the little text in the corner shows up and i can press ctrl and i can change mods, but when i press "m" nothing happens i got the fabric api,litematic and malilib all in 1.16.5,please help

**Comment by maruohon** [comment]
Which keyboard layout do you have?

If you have a different keyboard layout from QWERTY, then some of the keys could be something else, for example on AZERTY I believe instead of `M` it would be `,` ie. the key that is in the same place as `M` on QWERTY.

You can also get to the Litematica config menu via the mod list from the Mod Menu mod, to try if changing some of the keys would work.
