### ISSUE TITLE
More recent 1.17 Snapshot support

### ISSUE THREAD

**Issue by xradiusa** [maruohon/litematica#342]
Sorry if this isn't the right place to ask a question like this, but I was wondering if this mod is planned on being updated to the more recent 1.17 snapshots and if so what a time frame would look like. I was poking around in the code and found that it wouldn't be such a simple update because of the changes to rendering in Minecraft/fabric, which I guessed was a large reason it's not already updated.

**Comment by maruohon** [comment]
And you guessed right. I'm not currently working on any of the 1.17 snapshot versions anymore. In general chasing snapshots is just a weekly waste of my time, which further delays progress on the actual meaningful updates and improvements.

The earlier 1.17 snapshot versions of Litematica area already barely functional anymore, due to some smaller rendering changes in the earlier snapshots. Due to some of those changes the mod would just crash all the time when loading schematics or moving placements. I had to just disable/comment out the render threads to stop it from crashing for now, which also means that the rendering is super slow and laggy compared to normal (ie. compared to 1.16.x or earlier versions).

So currently I don't plan to update to any further snapshots or even the final 1.17 release (depending on when that comes out) before I'm ready to merge all the latest development code from 1.12.2 (via all the previous MC versions). One reason being the above mentioned rendering problems (it's most likely a threading issue in the mod), and I plan to entirely rewrite the renderer starting from 1.12.2. And as for a timeline for all of that to happen... basically I have no idea. I'm currently focusing on development on 1.12.2 for as much as I have modding/coding motivation to spare each day.

If you desperately want later snapshot builds of *some kind*, then check out skyrising's fork. He made a partial port to 21w10a. I'm not sure how much works and what doesn't, but it would probably at least help you hack together something that renders at least something.

**Comment by RealRTTV** [comment]
my day is ruined and my disappointment is immeasurable /j
