### ISSUE TITLE
BUILD NOT WORKING

### ISSUE THREAD

**Issue by handsoapwasher** [maruohon/litematica#358]
hey im confused on how to change all of this i am new to modding and this is my error code: * What went wrong:
Execution failed for task ':recompileMc'.

Unable to find a javac compiler;
com.sun.tools.javac.Main is not on the classpath.
Perhaps JAVA_HOME does not point to the JDK.
It is currently set to "C:\Program Files (x86)\Java\jre1.8.0_291"

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 12s
4 actionable tasks: 4 executed
if anyone can help me and walk me through all the steps that would be greatly appreciated! i am using command called : gradlew setupDecompWorkspace. I dont know how to change my directory from JRE To JDK. I am a beginner so please help

**Comment by maruohon** [comment]
Do you have a JDK installed at least? Usually if you install the JDK it should modify the environment variables automatically.

Also, what exactly are you trying to do, and for which MC version? Are you modifying or adding something to the mod? If not, then there are ready made builds available for all MC versions starting from 1.12.2 up to 1.17 atm. The 1.17 version is on CurseForge. The very latest builds for all the other MC versions are on my server (here: https://masa.dy.fi/mcmods/client_mods/), although there are also (sometimes not the latest) builds on CurseForge for everything except 1.12.2.

**Comment by handsoapwasher** [comment]
I do have jdk installed and changed the directory, but then a new error popped up. 
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type PluginResolutionStrategyInternal using BuildScopeServices.createPluginResolutionStrategy().

**Comment by maruohon** [comment]
You didn't answer my other questions or provide any more information so there is nothing further I can say, since I don't know what you are trying to do. Are you setting up a development environment or trying to build the mod? And for which MC version and mod loader?

**Comment by handsoapwasher** [comment]
Sorry yeah i want to set up the environment and iits on 1.7

**Comment by maruohon** [comment]
Actually 1.7 or 1.17?

You would have a very hard time trying to do anything for this mod back in 1.7, there are massive changes to vanilla code since then in countless places. The current build scripts in the `master` branch are for LiteLoader 1.12.2, you would have to adapt the scripts and all the versions back to 1.7 stuff first. And I don't even remember if there are Gradle things set up for 1.7 Forge development at all. You would probably be better off using Legacy-Fabric/Legacy-Quilt in that case.

If you meant 1.17, then check out the `temp_1.17_update` branch, and then run the `./gradlew genSources` command. You will need a Java 16 JDK for any 1.17+ development, whereas for anything up to 1.16.5 or even the 1.17 snapshot 21w18a Java 8 was enough.

**Comment by handsoapwasher** [comment]
Oh okay thanks for the help man
