### ISSUE TITLE
Strange blocks placement, and schematic's blocks 

### ISSUE THREAD

**Issue by varroo** [maruohon/litematica#401]
Hi, i'm using last version of both, litematica and malilib. (installed multiple times to see if the issue is gone, but is not). 
i play in a 1.17.1 server, and i use fabric
**Minecraft version**
Which Minecraft version are you playing on?

**Mod version and malilib version**
litematica-fabric-1.17.1-0.0.0-dev.20210713.103711.jar
malilib-fabric-1.17.1-0.10.0-dev.24.jar

**Description of the bug**

Mod works fine in all single player worlds and multiplayer world i've tried except for one (the one were i play).
Strange thing is that it always worked fine up to now, i use it a lot and on this server i used the 1.16 litematica, and then i also used the 1.17 version. But then suddenly it started give me this issue (no change at all, no mods added no server settings change, from one day to another it appears)

The problems are:
1 the auto placer doesnt work, it place block of the schematic but outside the schematic randomly around
2 when a block is place the schematic change some block apear as if they are from the schematic but they are not (so also without the auto placer is pretty difficult to use the mod)

3 (this is not a big issue) but when i started to record from xbox tool and also after i stop the recording M button to open litematica menu doesnt work at all, unless i restart the game (login off and in dont solve this porblem)

easyplacemode and easyplaceholdenabled are true but even false this problems still present

it think should be a server problems but other players use it normally and the server config are the same of when it worked also for me.

![2021-08-24_11 39 41](https://user-images.githubusercontent.com/89451613/130595342-7a153407-5812-47ca-82a9-0488b1f9ed6c.png)

in the image the schematic is made only from one layer of block but with autoplace the block are placed also above the layer (where air shold be) and only some of them are showed as wrong even if all of them are wrong. without autplace i place "blocks of schematic"  so no real blocks are there but the schematic is changed.

sorry if the request is confusing, but it's all very strange, I would be very grateful if you can give me some advice

**Comment by maruohon** [comment]
You must have been in the Schematic Rebuild mode then at least at some point. That mode is meant for editing schematics (I know the name is confusing atm, I need to rename it to Schematic Edit mode), so it allows you to place new blocks to the schematic, or break or change blocks in it (see the wiki for more info). So basically change out of the Rebuild mode to any other mode.

As for the Easy Place mode itself, it currently has at least one issue such that you need to first click on a schematic block, otherwise it does not "activate" properly. So if you were to click on air and then keep holding the use button (right click) and move your cursor over some existing blocks, then you would just get normal vanilla block placement all over the place. This has been fixed in 1.12.2 a long time ago, but not yet in any of the 1.13+ versions.

**Comment by varroo** [comment]
Solved! ty so much, i must have chenged the mode with the stick by accident. is there a way to change the stick to another item less used in survival from the settings?

**Comment by maruohon** [comment]
Yes, there is a `toolItem` config in the Generic config category to change the item. I never actually intended or expected people to keep using a stick as the tool so often, I just had to select some item as the default, where the tool functionality wouldn't interfere with normal gameplay by default. Personally I use and would recommend something like your normal food item as the tool, and then always just toggle on the tool functionality only when you actually need it, keeping it disabled most of the time (by default the hotkey to toggle it is `M + T`).
