### ISSUE TITLE
easyPlace mode is not working as intended

### ISSUE THREAD

**Issue by fujimite** [maruohon/litematica#405]
**Minecraft version**
1.17.1

**Mod version and malilib version**
litematica-fabric-1.17.1-0.0.0-dev.20210827.200417
malilib-fabric-1.17.1-0.10.0-dev.24

**Description of the bug**
Instead of placing the block my crosshair is on, it is placing all blocks behind that one. see https://streamable.com/ptwwr9

**Expected behavior** (if not clear from the description)
The block my crosshair is on should be placed.

**Screenshots**
https://streamable.com/ptwwr9

**Comment by maruohon** [comment]
Well, technically it is working as intended, as I added a new option `easyPlaceFirst` a few days ago, and it's disabled by default. Which means that the Easy Place mode now by default places the furthest block first, instead of the first block you are looking at.

But if people are used to the old behavior and if I would start getting bug reports about this change, then maybe I should flip that config to true by default to use the old behavior by default, before I upload these builds to CurseForge.

**Comment by fujimite** [comment]
oh, alright. thank you
