### ISSUE TITLE
Schematics don't move unless I press M+R

### ISSUE THREAD

**Issue by WaterExpensive** [maruohon/litematica#417]
Hello there, I've been encountering this issue for a while now and it's been bugging me a lot.
whenever I put a schematic inside my world I cant make it preview when I change its position unless I press M+R to restart it.
I see the box move, but not the schematics.
The Minecraft version is 1.17.1
And I'm using the latest release for litematica.
Thanks in advance.

**Comment by maruohon** [comment]
Then you are not using the latest version of Litematica. Two separate "placement doesn't move properly" issues were fixed in the latest 1.17.1 build. One of them being the "it doesn't move at all" issue, which was caused by a Lithium 0.7.4 change, the other one being the older 1.17+ issue of "the placement doesn't move/update properly more than 3 chunks away".

**Comment by WaterExpensive** [comment]
Ah, I must've not looked at the version right. Thank you for your time sir
