### ISSUE TITLE
When I used this mod, the game sometimes quit by itself and saved the file ! 

### ISSUE THREAD

**Issue by PeterShen666** [maruohon/litematica#419]
**Minecraft version** 
Which Minecraft version are you playing on? 
1.16.5

**Mod version and malilib version** 
litematica-fabric-1.16.4-0.0.0-dev.20201103.184101
malilib-fabric-1.16.4-0.10.0-dev.21+arne.2

**Description of the bug** 
When I put schematic in the game, the game quit by itself and saved the file.
Is this a bug?

**Comment by maruohon** [comment]
I would need to see the crash log or the `latest.log` file from the game session where the crash happens. But the first thing to check is how much memory do you have allocated for the game? With Litematica installed you generally need at least 2 GB allocated.

But also you are using *very* old versions of both mods.  Update both malilib and Litematica to the latest versions from here: https://masa.dy.fi/mcmods/client_mods/?mcver=1.16.5

**Comment by PeterShen666** [comment]
I assigned 3GB of ram to the game.I updated the mods to the latest version, but the problem still occurred. 
Here are the log file:
[minecraft-exported-logs-2021-09-19T13-55-56.log](https://github.com/maruohon/litematica/files/7192341/minecraft-exported-logs-2021-09-19T13-55-56.log)

**Comment by maruohon** [comment]
That crash seems to be caused by some other mod that does something with entity rendering. It seems that the schematic you loaded has some villagers, but for some reason the mod is trying to cast a `ServerPlayerEntity` into a `VillagerEntity`.

If you want to narrow down which mod it is, add the option `-Dmixin.debug.verbose=true` to the JVM arguments in your launcher/profile, and then launch the game and load into the world so that you get the crash. Then look at the console/log file, and look at which mods apply a Mixin to `class_922`, and it should be one of those mods.

**Comment by PeterShen666** [comment]
I tried, but it didn't seem to work. I can't find the mod that caused the crash.

**Comment by maruohon** [comment]
I don't know what you expect me to do if you don't give me any more information to go from. In the previous message I explained how you could narrow down which mod has the issue. If you didn't get that to work and don't show me any steps you did there (for example a screenshot of the JVM argument being set in the launcher) so that I could see if you did something wrong, then I can't do anything more to help with that. Alternatively you could just take out all the other mods you have either one by one, or half at a time (bisecting) to find the mod that has the issue.

**Comment by PeterShen666** [comment]
I found the problem. It is caused by this mod:Masa Gadget (Although this is a mod that optimizes your mod.)

**Comment by maruohon** [comment]
I found and fixed that bug and sent a PR for the fix: https://github.com/plusls/MasaGadget/pull/16

**Comment by PeterShen666** [comment]
Thank you so much for your help!

**Comment by plusls** [comment]
Thanks your pr!
New version is released, and fix this bug .

> I found and fixed that bug and sent a PR for the fix: [plusls/MasaGadget#16](https://github.com/plusls/MasaGadget/pull/16)
