### ISSUE TITLE
The guide is not removed after a block is placed

### ISSUE THREAD

**Issue by MzKaiser** [maruohon/litematica#438]
**Minecraft version**
1.17

**Mod version and malilib version**
malilib-fabric-1.17.0-0.10.0-dev.22beta.1
litematica-fabric-1.17.0-0.0.0-dev.20210616.033538

**Description of the bug**
I have a problem, it happens that when I place a block in the schematics, I keep getting the "hologram" as if I had not placed the block. The only thing I did was to load the schematic as usual and this happens to me, I am doing it with Sodium, this error started to happen out of the blue, and it happens to me with any other schematic.

**Comment by maruohon** [comment]
I'm assuming you also have Lithium 0.7.4?
The incompatibility with Lithium 0.7.4+, and also another similar issue of the schematic placement not updating further than 3 chunks away were fixed in the 2021-09-06 Litematica version for 1.17.1.

If for some reason you are stuck in 1.17.0 and can't update to 1.17.1, then you should be able to use the 1.17.1 versions of malilib and Litematica on 1.17.0 as well, as long as you don't try to add a schematic thumbnail/preview via the Schematic Manager menu. Doing that will crash if you mix the 1.17.0 and 1.17.1 mod vs. MC versions.

**Comment by MzKaiser** [comment]
Thanks for the quick reply, I do indeed have the lithium 0.7.4. I will deactivate it

**Comment by maruohon** [comment]
But why? That is like the only thing I didn't say to do... That latest Litematica version also has a ton of other fixes and small improvements.

**Comment by MzKaiser** [comment]
Okay, then I guess I'll install the latest version following the recommendation you gave me to prevent it from crashing my game.
