### ISSUE TITLE
Custom block state not working

### ISSUE THREAD

**Issue by Tanerx** [maruohon/litematica#449]
### Provide at least the following information
* **Minecraft version** - 1.16.5
* **Mod version and malilib version** malilib-fabric-1.16.4-0.10.0-dev.21+arne.5 - litematica-fabric-1.16.5-0.0.0-dev.20210917.192300

* **A clear description of the issue** - Change block state using debug stick and save with litematica. Before paste it look good but after blocks are pasted default. 
* Video: https://www.youtube.com/watch?v=G_aED6zVlpM

**Comment by maruohon** [comment]
Since you are on a server, the mod has to use regular `/setblock` commands for pasting. So there is no way for Litematica itself to suppress any block updates. Which means that either the command itself already updates the block, or setting the adjacent block updates it and it re-computes its placement state. If your server has the Carpet mod, then you can try if the `/carpet fillUpdates false` rule would prevent the blocks from updating in this case.

It works fine in single player, where the mod itself is able to suppress any block updates:
https://user-images.githubusercontent.com/2331050/143004000-ef898341-162b-4027-9030-813880681262.mp4

**Comment by Tanerx** [comment]
My bad. I thought the setblock command can work like minecraft:sandstone_wall[south=tall]. I just tried it, it doesn't work. The setblock command ignores the block state. 
Thank you for your time.

**Comment by maruohon** [comment]
It definitely does work for blocks that actually can stay in the given state, that's how Litematica pastes everything else such as bottom vs. top slabs, rotated blocks etc. Without looking at the code, I think for stuff like fences where the connection normally only happens if the adjacent block has a solid face on that side, it just resets or re-computes the block state at some point during the setblock.
