### ISSUE TITLE
Convert 1.18 schematic to 1.17.1

### ISSUE THREAD

**Issue by 2drocket** [maruohon/litematica#456]
Hi I have been attempting to paste in some schematics that are from 1.18 that do not have any new blocks or anything within as I would like to use them however when ever I try to use those schematics I am met with this error line, is there any possible way I could paste the 1.18 schematic into a 1.17.1 world? 
![unsupported](https://user-images.githubusercontent.com/64994697/144836560-dab857b1-be34-43c1-9c0c-46cd26f3af79.jpg)

**Comment by maruohon** [comment]
I bumped the schematic version because there was a tiny change to the scheduled block tick data format. The downside of that bump is that the mod for all the previous MC versions now refuse to load it... Maybe I'll have to release a small update for 1.17.1 that allows loading that schematic version. But in the mean time, if you have an NBT editor such as NBTExplorer, you can just change the schematic version to 5 in the file and then you can load it in any of the 1.13+ versions of the mod (obviously new blocks added in each MC version being the limiting factor).

**Comment by abruncke** [comment]
Sort of related but not sure if it is a separate issue; I updated to 1.18 (litematica-fabric-1.18.0-0.0.0-dev.20211203.013300) and copied over all my schematic files from 1.17 but none show up in the "Load Schematic" option in 1.18. Do I need to convert or import or something?

**Comment by maruohon** [comment]
@abruncke Check your path in the schematic browser. If you also copied over the Litematica configs, then all the schematic browser menus will still be pointing at your old Minecraft installation location's schematics directory. Clicking on the `Root Directory` button makes it jump to the current `.minecraft/schematics/` directory.

**Comment by abruncke** [comment]
User error... embarrassed to say I was copying the contents of config/litematica/ rather than the /schematics folder... sigh.  Thanks so much for the quick reply and "solution"  :)

**Comment by maruohon** [comment]
The latest 1.17.1 version allows loading version 6 schematics from 1.18.x, so I'm closing this.
