### ISSUE TITLE
Selection box not appearing

### ISSUE THREAD

**Issue by Aurumaker72** [maruohon/litematica#459]
### Repro
On Minecraft 1.18, creating a selection using the Area Selection Manager > New selection will not show selection boxes, even after moving the corner coordinates.

*expected behaviour: the selection box appears near the player*
*manifested behaviour: nothing appears near the player*
![image](https://user-images.githubusercontent.com/48759429/145688263-1f079a39-d5d9-4047-a1cc-427024de2c62.png)

### Info
malilib full name: `malilib-fabric-1.18.0-0.10.0-dev.26`
litematica full name `litematica-fabric-1.18.0-0.0.0-dev.20211203.013300`

This issue is not caused by sodium or other optimization mods; I have verified this by removing all mods except the malilib library and litematica (and the fabricapi).

### Addendum
Schematic rendering is invisible too. This is most likely due to me not enabling something in the options, altough I have checked and tested with and without additional modifications.

**Comment by Aurumaker72** [comment]
Resolved by using area editor instead. HOWEVER the previous method I used in 1.17 and it still displayed the selectionbox, so this definitely broke in 1.18

**Comment by maruohon** [comment]
Nothing was changed (like, ever, in the 1.13+ versions after the last port from 1.12.2) in the area selection code. However I did one small "config" change in the 1.18 port that I've meant to do for ages: I changed the default area selection mode from `Normal` to `Simple`. This means that if you didn't change it back to `Normal`, then any areas and changes you make by going all the way through the Area  Selection Manager menu are not the actual active area being used. The Area Editor menu (for example the button in the main menu, or the direct hotkey) on the other hand would always lead to the actual active area.

I realize this is probably one of the more confusing parts of the mod for many users, and there are no good resources or tutorials that would actually explain how these two modes work and differ.

Basically the `Normal` mode was the only selection mode in the mod originally. (I should probably rename it instead to `Multi-Box` or `Multi-Region` now.) This `Normal` mode supports an arbitrary number of separate sub-region boxes in the same selection, and because of this that mode also saves each of these "area selections" into a separate save file, which are the things you create or select via the Area Selection Browser. This is so that you can work on multiple things "simultaneously" or rather in succession, and still go back to an older selection without having to re-do possibly a large number of sub-region boxes. (If you for example need to make some fixes to the original build and save it again as a new version of the schematic.)

But because of the extra step of having to use the Area Selection Browser to first create a "selection file", this is a small annoyance/extra complication/confusion to some users, and quite often you actually only need a single selection box/sub-region so it's also kinda inconvenient even for "power users" of having to do that extra step. So this is why the `Simple` selection mode was added at one point. While in the `Simple` mode, the Area Selection Browser and the separate selection save files are not used at all. Instead there is just one "global" (still per-world or even per-dimension I think?) selection, which only has one sub-region box. You can't create more sub-regions nor delete the one. So in the `Simple` mode you don't have to do *anything* else than point and click to se the selection (or use the Area Editor if you want to input coordinates manually).

Now the confusing part that happened in your case is that if you still do go to the Area Selection Browser and create a selection, and use the `Configure` button there, you are then editing that normal mode selection, but that is not the active selection due to the `Simple` mode overriding the active selection to the "global simple mode selection". I believe many of the menus should be giving you an orange warning text that you are in the `Simple` mode. But I guess without knowing about these design and implementation principles that warning probably doesn't mean much, does it? I wonder if I should completely hide the Area Selection Browser button and also prevent that hotkey from working while you are in the `Simple` mode, to maybe lessen this confusion?

**Comment by Aurumaker72** [comment]
Thank you for the explicit response.
>  I believe many of the menus should be giving you an orange warning text that you are in the Simple mode

It did sadly not appear to show any warning status on any controls. 

And I kind of disagree with hiding entire controls conditionally; maybe just disable it and give reason for disabling inside of tooltip
![image](https://user-images.githubusercontent.com/48759429/146609135-3b07864d-55ab-4959-8c2c-75fb098594f6.png)
