### ISSUE TITLE
Easy Place Mode not placing some blocks

### ISSUE THREAD

**Issue by DanrejkNotes** [maruohon/litematica#465]
After the update for 1.18 placing some blocks from schematic using the Easy Place mode causes "ghost blocks" to be placed. So basically places the block only client side.
I know this issue applies to stairs and leaves, but might be more. I didn't do much reaserch.

**Comment by maruohon** [comment]
Are you on a server? What type of server? You may need to change the Generic -> `easyPlaceProtocol` option depending on the server you are on:
* Set it to `v2` if you are on a server that has CarpetExtra (or otherwise supports the Carpet Accurate Block Placement protocol)
* Set it to `Slabs only` if you are on any Spigot/Paper server variant (or even any server that doesn't support the Accurate Block Placement protocol)
* Set it to `v3` if you are in single player, it has the best support for different block types
