### ISSUE TITLE
NullPointerException: Cannot invoke

### ISSUE THREAD

**Issue by SparkdotIe** [maruohon/litematica#506]
Now I'm playing with a lot of mods so any of them could be messing with it. 
my suspect since it seems to have to do with rendering, is Sodium or one of the child mods I have for it... I'm not good with this stuff tho so I could be 100% wrong here

here's a Crashy: https://crashy.net/RCLrACZkPiRqDeE495Ef
and a byte bin: https://bytebin.lucko.me/Is1Ygzhug4

feel free to roast me if I'm just being stupid, or if I missed something that is needed to make this a full report

**Comment by maruohon** [comment]
I've seen a similar crash reported a few times, but no clear reason yet what causes it. But basically somehow Litematica seems to fail to create the schematic world. I'm fairly certain it has to be some kind of mod conflict. In one case it somehow seemed to be caused by... Continuity I think? But it doesn't really make sense why that mod would affect the schematic world creation, and you don't seem to have it installed anyway.

Does this crash happen immediately after logging in to a world, and every time? So in other words have you been able to use Litematica at all yet? If it happens consistently then I may need to make a test build with a bunch of debug prints all over the schematic world creation code and then have you try that to see if I could narrow down where it fails and how.

**Comment by SparkdotIe** [comment]
It happens a few seconds after being in, on the first load of the instance and only the first load. Since I'm using Not Enough Crashes I'm able to go back into the world from the title screen and it seems to load litematica fine after the first crash. Though I've yet to try using it, having just disabled it for the time being.

If the world has been loaded without litematica it seems to work fine without crashing.

 Among the stated problem before, after the crash it seems that rendering of entities including the player model and items, just doesn't happen. Leaving all entities invisible.
 
 It is consistent, but only on first load as previously mentioned.

Forgive the slightly late response.

this is in a world that crashed, and, obviously on an instance after a crash. WITHIT displays there's a zombie there though no rendering happens.
![2022-03-21_15 00 05](https://user-images.githubusercontent.com/26665237/159354526-1daa4b36-06a6-40d6-9085-8ff7725b128e.png)

this is in third person, showing that I am also not rendered.
![2022-03-21_15 00 12](https://user-images.githubusercontent.com/26665237/159354507-f2a37331-5fd9-4f23-a5f1-c48f1a998fa2.png)

This is on a world that didn't crash, but on an instance that crashed.
![2022-03-21_15 08 19](https://user-images.githubusercontent.com/26665237/159355355-62365675-6e01-44f5-b5ab-a855bcc87b87.png)
