### ISSUE TITLE
Middle clicking on "hologram" block doesn't always bring that block to hotbar

### ISSUE THREAD

**Issue by Aefinn** [maruohon/litematica#569]
### Provide at least the following information
* **Minecraft version** *
1.19.2
* **Mod version and malilib version** 
litematica-fabric-1.19.2-0.12.4 and malilib-fabric-1.19.2-0.13.0

* **A clear description of the issue** 
Had the schematic on and blocks were in my inventory but when I middle clicked a block to get it from my inventory to my hotbar to place it, the blocks flashed in the hotbar and then went back to inventory leaving that hotbar slot empty. For some reason sometimes it works normally, sometimes it doesn't. Only thing I have noticed is that if I have myself put it into the hotbar and later need it again, then it works. But if it hasn't been in hotbar yet then it might not work. 

This only started to happen after updating from 1.19 to 1.19.2

**Comment by Aefinn** [comment]
Here is a small video showcasing this bug https://youtu.be/3XSHT3JATOA

**Comment by maruohon** [comment]
I was going to suggest checking your `pickBlockableSlots` config, as I recently fixed a bug with it and made it more strict, and also made it not replace any tools in the hotbar in the allowed slots.

But since it does pick block it momentarily and something just moves it away again, I don't think the issue is with the pick block feature itself(?) Does this also happen in single player, if you set up your hotbar/inventory in the same way and try to pick block the same block from the schematic? Maybe it's some kind of server-side plugin that prevents the pick block since it detects that you are not looking at that block in the actual world(?) No idea if there is a plugin or something that would be checking for that.

**Comment by Aefinn** [comment]
I do not believe it's a server-side plugin preventing this since I'm of the admins on the server and we haven't changed any of our plugins and it did work previously. That said, in a short test I couldn't replicate the issue in single player world. But it was a short test and this doesn't happen 100% in server either.

**Comment by Aefinn** [comment]
Hmm. I think I might have found the culprit. It seems that Inventory Profiles Next has added a new "feature"

_Picked up items will now go directly into the inventory instead of taking hotbar space. This can be changed in the Locked Slots tab of the config._

I turned that off and in small test the items seemed to work normally again.
