### ISSUE TITLE
Re-Binding GUI keep Issue

### ISSUE THREAD

**Issue by TangoDown** [maruohon/litematica#614]
So I rebound the GUI key to Page Up on my keyboard, and now I cannot get the GUI Menu to open. It's a Kingston Erginomical Keyboard (Standard Layout) with no Frills, no Thrills on a Windows 11 PC. 

Is there a file I can delete to Remove all the Keybinds for this one mod or a command I can type in chat?

**Comment by maruohon** [comment]
Did you re-bind both `M` and `M + C`? You can get to the config menu via both of those, and also if you have the Mod Menu mod installed, you can also open the config menu via the mod list. And the final option is to edit or remove the config file at `.minecraft/config/litematica.json`.

**Comment by TangoDown** [comment]
I downloaded Mod Menu and was able to fix the issue. I didn't realize I had to enable Empty Keybinds.

**Comment by maruohon** [comment]
> I didn't realize I had to enable Empty Keybinds.

I'm not sure what you mean?

Page Up is already used in two of the render layer related hotkeys, but that alone doesn't "break it" for the main menu hotkey. On the other hand the main menu hotkey by default is set to be exclusive and trigger on release, so that *would* make it conflict with the render layer hotkeys, unless you flip those options or change the render layer related hotkeys to something else. (Those options are needed for `M` to work alone as a hotkey, on release, even though there are other hotkey combinations such as `M + T`, `M + R` etc. that should not trigger it.)
