### ISSUE TITLE
1.7.10?

### ISSUE THREAD

**Issue by gubk114514** [maruohon/litematica#631]
1.7.10 ?

**Comment by Coathar** [comment]
https://www.curseforge.com/minecraft/mc-mods/schematica

**Comment by HiddenCirno** [comment]
> 

curseforge just have 1.9....

**Comment by Coathar** [comment]
https://www.curseforge.com/minecraft/mc-mods/schematica/files/all?filter-game-version=2020709689%3A4449

**Comment by HiddenCirno** [comment]
> https://www.curseforge.com/minecraft/mc-mods/schematica/files/all?filter-game-version=2020709689%3A4449

oh thx

**Comment by maruohon** [comment]
It's extremely unlikely that there would ever be backports of Litematica to anything older than 1.8 (at least not by me). The jump from 1.8 to 1.7 would be hugely painful because there was no BlockPos and no block states and no block models before 1.8. And even 1.8 and 1.9 would already cause issues and need to drop at least some block rotation support, because that code didn't exist yet in vanilla before 1.9/1.10.
