### ISSUE TITLE
How to replace top slab by another type of top slab

### ISSUE THREAD

**Issue by JulienTant** [maruohon/litematica#66]
Hi,

I'm trying to replace a top slab by another kind of top slab but always end up having bottom slab placed. Is there a way to do that ?

**Comment by SunSerega** [comment]
Maybe something like `minecraft:slab_name[half:top]` ? What feature you are actually talking about, and how exactly you use it?

**Comment by maruohon** [comment]
I can't test this myself atm because I'm in the middle of moving... but:

It's supposed to work by just clicking on the top half side of a block in the rebuild mode, just like your would normally place a top slab. Does that still result in a bottom half slab? If it doesn't directly work when clicking on the old top slab, then how about if you temporarily switch it to some other full cube block that doesn't exist in the schematic otherwise, like maybe bedrock or diamond blocks or something, and then try the rebuild on the side top half of that block? It might be some weird interaction with the vanilla slab placement code. Although clicking on the side of a top slab should just place a top slab, so I would imagine it should work...

If neither of these work, then the new "state storing" feature that is already in the 1.12 code base and will be coming to the 1.13+ versions with the next merges at some point soon-ish, does allow doing this. Using that you would just Alt + click on the new top slab block to remember/store that state (just like in the Fill and Replace modes), and then in the rebuild mode right click with an empty main hand, if I remember right, to use that stored state instead of using the held block.

**Comment by JulienTant** [comment]
Hi,

I ended up using minecraft /fill command to replace my blocks and then created a project above my construction in creative. Then i tried again.... and it worked. So it's on me, i messed up something obviously but don't know what/how. 

Thanks!

**Comment by Helheim7** [comment]
Hi,

I'm also having this issue - did anyone figure out how to do this without having to use commands? Bottom slabs have no issues; just the top ones always end up as bottoms.

Thank you!

**Comment by maruohon** [comment]
Here is a quick & dirty video explaining it a little bit (I also already explained it in the above comment to some extent): https://youtu.be/z6lnWPLmBmM
