### ISSUE TITLE
Schematics disappearing when closing Minecraft

### ISSUE THREAD

**Issue by tomosmc** [maruohon/litematica#679]
Whenever I close and reopen my Minecraft, all my loaded schematics and schematic placements are gone, and I would have to click load schematic and set it up on the right coordinates again. In my config > litematica folder there are a lot of json files, including the name of my schematics and "litematica_*servername*_dim_dim_minecraft_overworld. I'm on 1.19 on a server.

Interestingly, I'm finding out that on a singleplayer world it has remembered my schematic from more than a week ago. Any ideas?

**Comment by maruohon** [comment]
Are you on a Realm server? Do you have lots of config files with different server addresses? Or do you maybe have some whitespace characters in the beginning or end of your server address in the server list? Check via the Edit menu. (This was something I fixed a while back in 1.12.2, but that fix isn't yet in any other MC versions I don't think. Having a white space at the end of the server address broke loading the configs back from the file, because the name didn't match. I think Windows doesn't allow a space at the end of the file name or something?)

**Comment by datlemonylime** [comment]
did you fix this im having the same issue with it and idk what to do i have been trying to fix for a hour now and nothing

**Comment by tomosmc** [comment]
Yes, I noticed that they would reappear by logging out, going into a singleplayer world and then going bak to the server.
