### ISSUE TITLE
Litematica not loading schematics?

### ISSUE THREAD

**Issue by ThayerFletcher** [maruohon/litematica#703]
Minecraft version 1.19.2
Litematica version 0.12.7
MaLiLib version 0.13.0

I've been using litematica for a couple months now, playing on my private smp with my friends to make builds and stuff. But recently when I try to load schematics, none are able to load. It says the whole "loaded to memory successfully message." but the holograms do not show up at all. Yet when I check the loaded schematics, it shows that they are there. Even after I reload, unload and then reselect the holograms, refresh my chunks, set my render distance low, restart my game, and my server, nothing works. Yet when I go on my singleplayer superflat, the holograms show up and it has me utterly baffled. I don't know what the problem is, please help. 

Edit: My render mode is set to "All" so it's not that I think.

![2023-05-17_19 04 18](https://github.com/maruohon/litematica/assets/133925441/1999e623-2f24-46a8-9f95-ec24e0274587)

![2023-05-17_19 04 28](https://github.com/maruohon/litematica/assets/133925441/0bd6d02f-7064-4d91-9f1e-e2de52234b4b)
![2023-05-17_19 04 42](https://github.com/maruohon/litematica/assets/133925441/b839fe7a-0ae8-43f3-84c3-e3a4af1b0d0b)
![2023-05-17_19 04 58](https://github.com/maruohon/litematica/assets/133925441/717e7e51-d2ea-45cb-ae45-d2499a7a8c01)
![2023-05-17_21 13 28](https://github.com/maruohon/litematica/assets/133925441/04bfc0e5-bbe9-4269-97a2-471c25b3372c)

**Comment by rycbar0** [comment]
have you checked your config? maybe the renderer is stuck in layer mode and only renders some off the way layer.

**Comment by ThayerFletcher** [comment]
> have you checked your config? maybe the renderer is stuck in layer mode and only renders some off the way layer.

Yeah I did. It's set to "All" actually. I will add it to the edit.

**Comment by maruohon** [comment]
You have (accidentally?) unchecked the option to automatically create a placement of the loaded schematic.
![image](https://github.com/maruohon/litematica/assets/2331050/7bfb7224-9d73-4370-b00c-1b8225e42bc3)

Litematica separates the concept of loading a schematic to memory from placing that schematic to a world so that it's actually visible/usable in any way. This allows you to place the same loaded schematic in multiple locations in the world, without having to load it to memory multiple times. So a "schematic placement" is basically the position, rotation and mirror information for one "placed instance" of a loaded schematic.

Because of this looking in the Loaded Schematics menu is actually sort or irrelevant for figuring out what is supposed to be visible in the world. Instead you should look in the Schematic Placements menu, as those are the visible instances of (at least some of) the loaded schematics (the ones that are enabled).

**Comment by ThayerFletcher** [comment]
> You have (accidentally?) unchecked the option to automatically create a placement of the loaded schematic. ![image](https://user-images.githubusercontent.com/2331050/239254006-7bfb7224-9d73-4370-b00c-1b8225e42bc3.png)
> 
> Litematica separates the concept of loading a schematic to memory from placing that schematic to a world so that it's actually visible/usable in any way. This allows you to place the same loaded schematic in multiple locations in the world, without having to load it to memory multiple times. So a "schematic placement" is basically the position, rotation and mirror information for one "placed instance" of a loaded schematic.
> 
> Because of this looking in the Loaded Schematics menu is actually sort or irrelevant for figuring out what is supposed to be visible in the world. Instead you should look in the Schematic Placements menu, as those are the visible instances of (at least some of) the loaded schematics (the ones that are enabled).

Oh my god I feel so stupid. Thank you so much. Sorry for wasting your time. And yes it was an accident I didn't even realize.

**Comment by ThayerFletcher** [comment]
Great support and help.
