### ISSUE TITLE
[Suggestion] Allow substitutions such as Glass -> Black Stained Glass in the material list

### ISSUE THREAD

**Issue by xc0ff33** [maruohon/litematica#706]
**Is your feature request related to a problem? Please describe.**
Sometimes, a schematic involves glass, slabs, walls, planks, and similar blocks that come in different colours or looks but won't affect the structure, especially if it is a farm of some type (personally, I use the mod for help building complicated farms) and different colours of glass or different types of wood would change the colour of the farm without the rates of the farm lowering.

**Describe the solution you'd like**
It would be great if there could be an option to change every, for example, glass block in the schematic to black stained glass. For example, if a farm or contraption requires cobblestone walls, but it is easier for the player to get deepslate walls, deepslate walls could still be used without changing the actual farm's production.

**Describe alternatives you've considered**
Currently, I have to paste the schematic in a creative world and manually change glass to black stained glass, then save the schematic again.

**Additional context**
(a button like this could be added)
![image](https://github.com/maruohon/litematica/assets/126925753/8c9d22c0-4bab-48dc-8be8-f806c7200dbd)

**Comment by maruohon** [comment]
You can use the [Schematic Edit mode](https://github.com/maruohon/litematica/wiki/Schematic-Editing) to change blocks in the schematic, without pasting it to a temporary world.

You are specifically looking for the `schematicEditReplaceBlock` hotkey in this case.

Later on there will also be some kind of GUI alternative to changing blocks, but I'm not sure if it will work via he material list GUI, because due to the way things are implemented, the material list actually has no direct relation back to the schematic anymore.

**Comment by xc0ff33** [comment]
Thank you, I totally didn't know about this feature. Thank you for your reply!
