### ISSUE TITLE
Materials list not updating

### ISSUE THREAD

**Issue by schomm** [maruohon/litematica#71]
I'm working on mapart so it would be sweet to be able to see how many resources I have left but the materials list simply says I haven't done any progress at all and just shows the total materials even though I've already placed a good chunk.

**Comment by vacla** [comment]
have you clicked the button refresh list in material list?

**Comment by schomm** [comment]
Yes, many times, still nothing

**Comment by maruohon** [comment]
Did you open the material list from the placement config GUI or using the hotkey? Or did you open it from the schematic loading menu? Only the material list for a placement will count blocks from the world and show progress. A material list for a schematic doesn't check the world at all, it's calculated for a schematic directly.

**Comment by schomm** [comment]
I used the materials list in the schematic loading menu, I tried enabling the HUD and I think it works? It requires a total of 5,5k coal blocks and I haven't placed them all though the GUI list shows it as all are placed or I just don't understand how the list works.

**Comment by SunSerega** [comment]
As @maruohon said in prev message, materials list in the loading menu takes materials from file and doesn't care about world. You need a placement materials list, because you can have multiple placements of same schematic in same world. Otherwise there is no way to know for which placement materials needs to be calculated.

Btw @maruohon how about add some global material list, of all schematics in the world (counting only materials loaded chunks).
