### ISSUE TITLE
Sub-regions

### ISSUE THREAD

**Issue by ItzTodesPlayz** [maruohon/litematica#716]
Hi :)
Hope you are having a good day.

How do you make more than one sub-regoin?

Please show me in a YouTube video or picture step by step with discription step by step.

![16870474773032388797474013521135](https://github.com/maruohon/litematica/assets/106039985/309cc0ba-ec8c-4dba-a00d-bf35b0054a28)

**Comment by maruohon** [comment]
You make an area selection in the "Normal"/Multi-Region mode, instead of the Simple mode. The Simple mode is hard coded to only have one region/selection box.

* First switch to the "Normal" mode, in the middle left of the Litematica main menu.
* Then create a new "area selection save file" via the Area Selection Browser menu. (Or select an older existing selection if you want to continue working with it.)
* Then use the Area Editor menu to create, rename and control the sub-regions. The default hotkey to directly open the Area Editor is numpad multiply.

These Normal mode areas are saved to separate save files on the hard drive so that you can switch between different selections easily and still use the selections again later if needed. That way you don't have to re-create a possibly very complex selection again if you need to select something else in the mean time.

![litematica_multi-region_area_selections_howto_2](https://github.com/maruohon/litematica/assets/2331050/7bd7bf2e-e95e-4e22-8781-f8b6e32f6e2e)

![litematica_multi-region_area_selections_howto_3](https://github.com/maruohon/litematica/assets/2331050/564d5a91-7add-43d0-8d66-3210f1ab0a47)

![litematica_multi-region_area_selections_howto_4](https://github.com/maruohon/litematica/assets/2331050/29dcc14b-7788-42b0-a892-eeadc224e27f)

![litematica_multi-region_area_selections_howto_5](https://github.com/maruohon/litematica/assets/2331050/92831129-dc4b-4e6b-b9fb-bda23bf63885)

![litematica_multi-region_area_selections_howto_6](https://github.com/maruohon/litematica/assets/2331050/60c39ba4-61eb-4a9b-abfd-8cc8c5b60e0d)

You want to be in the Area Selection tool mode if you want to use the tool to control the selection. You can middle click with the "tool item" to select either the region boxes as whole or one of their primary/secondary corners to control with the tool. Then you can left or right click to place/move the corners, or Alt + scroll to nudge around the selected element in the direction you are looking at.

Also I highly recommend using the `Expand` corner behavior mode instead of the default `Corners`. You can switch between those modes with `Ctrl + M` in the Area Selection mode, or using the button in the Area Editor menu.

In the default `Corners` mode you `left click` to set the primary corner, and `right click` to set the secondary corner. (Sneak to set it adjacent the pointed block instead of inside it.) But in most cases you don't have blocks in the exact corners of the build, so then you would need to use temporary blocks and derp pillars. That is just unnecessary.

In the `Expand` mode you `right click` to collapse the selection box to the clicked position, and then you can `left click` multiple times to expand that selection around all the blocks you click on. This way you can always select what you want without using any temporary blocks at all. (Unless you also want to select some air around it... but then you can select a corner and Alt + scroll nudge it.)

There are also some related hotkeys for controlling selection boxes. The most useful of them is probably `selectionGrow`, which allows you to auto-grow the selection box around a free floating build. So you would just right click once in the Expand mode to set the initial box somewhere in the build, and then use `selectionGrow` to automatically grow the selection box around the entire build. Note that there must not be any adjacent/touching blocks outside the build, and thus the build can't be on the ground for this to work. Otherwise the selection will just grow around the entire loaded chunks area around the player. The way this grow feature works, is that it expands the box by one block on each 6 sides, and then it checks if that new shell contains at least one block that is not air, and if it does, then it keeps that expansion. And it repeats the expansion as long as there are blocks in the grown new shell.

Here is a 5 second "tutorial" for saving a schematic using the Expand selection mode and the `selectionGrow` hotkey ;)
https://streamable.com/70pmm

**Comment by ItzTodesPlayz** [comment]
Thank you so much and hope you have a great day every day ;)
