### ISSUE TITLE
New schematics won't load in one specific world

### ISSUE THREAD

**Issue by CurseTail** [maruohon/litematica#724]
I mainly make schematics in my creative world to build them in my survival world, it had worked for a long while, until suddenly my survival world wouldn't load anymore schematics, despite me unloading ALL other schematics. This isn't a simple "Lines show up, but there is no viewable schematic", nope, no lines, no schematics show up in the "Schematic Placements" tab, and this is world exclusive, the schematics load in any other world, except for that world. So there doesn't seem to be any mod conflicts, sure, I use OptiFine, but I know the conflictions with shaders and litematica so I never use them together unless I'm getting a screenshot and I happen to have one loaded. So I have no idea what's happening.

I am on Fabric 1.19.4 if that helps.

**Comment by maruohon** [comment]
Do you mean you don't get *placements* in that world? (But the schematics are still in the Loaded Schematics list?)
Have you accidentally unchecked the `Create placement` checkbox above the `Load Schematic` button? In that case the schematic gets loaded, but a placement won't automatically get created.

You can also create placements "manually" from the Loaded Schematics list, in case you need the same schematic placed multiple times in different locations for example.

**Comment by CurseTail** [comment]
There is nothing in the "Loaded Schematics" tab either, yet whenever I try to load a schematic it says "Schematic (Insert Schematic Name Here) successfully loaded into memory", yet nothing appears in "Schematic Placements" or "Loaded Schematics". And to clarify this again, this issue only happens in one of my worlds, not any others.

**Comment by CurseTail** [comment]
Okay, thank you, did not notice that was turned off on my survival world (Yet not any other worlds). (Edit: When I originally read your response, I initially thought "Well it is checked in my creative world, or else it would do the same thing." Turns out my initial assumption was incorrect.)

**Comment by maruohon** [comment]
That doesn't make sense to me... The `Create placement` value is saved in a per-world config file, so that was the "obvious" thing that could cause this (and has happened to a few people before). But there is nothing related to any config files that would affect simply loading schematics to memory.

If it says it was loaded successfully, then it should appear in the Loaded Schematics list. Note that without a placement referencing them, if you log out or change dimensions, then all of them will get unloaded for good, as nothing would load them back when re-joining the dimension.

So AFAIK this should not be possible in the "official" base mod. Do you have other mods that might be modifying Litematica stuff? You can also try moving out or deleting the per-world config files for that affected world from `.minecraft/config/litematica/litematica_worldname*.json`.

Ah okay I see you solved it. Well I'll leave what I already typed here anyway... Maybe it will help one person at one point several years in the future or something... :p
