### ISSUE TITLE
Config Menu doesn't pop-up when M+A(/A)(/M) is held!

### ISSUE THREAD

**Issue by MrScarfy** [maruohon/litematica#864]
I don't know why but when I press the hotkeys that are supposed to open the config menu for litematica it doesn't seem to work. I am on version 1.20.4 and I have all the required files. I even opened the litematica.json file and looked what the hotkeys where, but I found nothing but what you can see in the following image; 
![image](https://github.com/maruohon/litematica/assets/173718983/8d54df7c-b2ff-4d49-98b2-0f2847de4dbd)

How do I fix this?

**Comment by maruohon** [comment]
First things first. Is the mod actually loaded? Do you see the orange Litematica text o the F3 screen? (I guess it is if it generated the config file...) Do you have other mods that have keys bound to `M`, such as a minimap mod?

If you have an non-QWERTY keyboard layout then the keys may be different, for example instead of `M` it would be `,` on AZERTY.
If you have the Mod Menu mod then you can open the config menu via the mod list as a fallback, to try and change the main menu or config menu hotkeys.

**Comment by MrScarfy** [comment]
Yes I do have it installed + No I don't have any other mods with the M Key bound to anything.
By the way I searched deeper in the .JSON file and found something with the GUI bound to KP_MULTIPLY, What does this mean

**Comment by maruohon** [comment]
The Area Editor menu is by default bound to the multiply key on the numpad.

So which keyboard layout do you have?
Does neither `M` nor `M + C` work? How about the malilib config menu `A + C`?

**Comment by MrScarfy** [comment]
No, I tried. I changed KP_MULTIPLY key to O to see if would work and it still doesn't

**Comment by MrScarfy** [comment]
Wait I reset the config file and it changed itself back to KP_MULTIPLY but if I press , it works now
(I forgot to tell you I had an AZERTY keyboard cuz I was eating a wrap lol) 
1 more thing, why is the keybind * (KP_MULTIPLY) for openGuiAreaSettings and what does it do? Same thing with openGuiPlacementSettings it's set to - (KP_SUBTRACT)

**Comment by MrScarfy** [comment]
Thx for all the help btw!
I know little to none creators that are so active with their mod-users!
Ur 1 of the first lol, Congrats🥳!

**Comment by maruohon** [comment]
"Why". Because I just chose those as the default hotkeys for those two menus...

Area Editor is the menu where you can manage the area selection while you are selecting stuff. And the placement configuration menu hotkey is a shortcut to open the placement configuration menu for the currently selected schematic placement.

If you are new to the mod, maybe watch one or more of these tutorials. These are the 3 best beginner tutorials I've watched so far (in no specific order):
* https://www.youtube.com/watch?v=aMZSXAKZzpo
* https://www.youtube.com/watch?v=zHZLvJgpRag
* https://www.youtube.com/watch?v=KhvEs_iMBjU

**Comment by vacla** [comment]
With azerty, you need to use: , + C

**Comment by MrScarfy** [comment]
Thx Vacia
Also Maruohun, While trying to figure this is out I was watching 3 of the tutorials of SaminUP for downloading Fabric, Installing the mod & How to use it! But thx anyway, Ur the best!
