### ISSUE TITLE
Schematic  Verifier is not that useful

### ISSUE THREAD

**Issue by FASTB1mc** [maruohon/litematica#886]
The Schematic verifier is useful for telling you that things are wrong but not where they are wrong. 
I would appreciate a sight addition to the Schematic verifier that will show coordinates of where the blocks are wrong or in the wrong state. The only thing I can do right now is fly around my build and try looking for the wrong blocks.

Thanks.

**Comment by maruohon** [comment]
The verifier does have that. You need to select the errors you want to see, by clicking on either the individual error (block mismatch pair) on the result list, or one of the colored "type headers" to highlight all of that type (like Wrong State).

Also note that in the current 1.13+ mod versions for the in-world markers to render, that placement has to be selected (click on it in the Schematic Placements list so that it has the white selection outline).

**Comment by FASTB1mc** [comment]
ok thanks. I should look harder next time.
