### ISSUE TITLE
1.15

### ISSUE THREAD

**Issue by Andrews54757** [maruohon/litematica#94]
Hello.

I have been trying to make this mod work for 1.15 -- it seems that the snapshot version of this mod does not work with it.

So I have been making changes to try to make it work. But I am coming across several problems.

1. Malilib library - The library is not published for 1.15 yet, so I am trying to figure out how to build it manually
2. Fixing incompatibilities - There seems to be a lot of variables/classes that have been changed, I have tried to fix them, but it seems that it has not been working.

I think I am doing something wrong since the amount of work I think I need to put into this to make it work seems unreasonable for just a small upgrade. Is this correct? What are your thoughts @maruohon ?

Thanks

**Comment by Andrews54757** [comment]
<img width="1346" alt="Screen Shot 2019-12-13 at 9 48 56 PM" src="https://user-images.githubusercontent.com/13282284/70842495-627ef500-1df2-11ea-8834-93a856baddca.png">

^^^ This seems unreasonable.

**Comment by Andrews54757** [comment]
It seems that viscode did not find the generated sources... (how? I did run genSources)

**Comment by maruohon** [comment]
There is already a 1.15 build of Litematica here: https://pena2.dy.fi/tmp/minecraft/mods/client_mods/

The rendering rewrites in vanilla after snapshot 19w37a were quite a bunch of work this time, especially for Litematica.

**Comment by jysocial** [comment]
I cant help with coding issues, but I can tell you that 1.15 builds exist on Masa's website here https://masa.dy.fi/tmp/minecraft/mods/client_mods/

**Comment by Andrews54757** [comment]
@maruohon @jysocial Thanks everyone. I found it.

Is it always such a pain to update mods like this? I can't believe modders have to deal with this every update.

**Comment by maruohon** [comment]
The amount of work varies a LOT by mod and by MC update, it just depends on which vanilla systems they are rewriting and what the different mods touch in vanilla. For example Item Scroller needed basically no changes from 1.14.4 I believe, except for some renames in Yarn (part of the Fabric project). But anything that did any significant rendering needed to adapt to the new vanilla rendering in 1.15.

**Comment by Andrews54757** [comment]
I see. Well, keep up the good work @maruohon!

Closing as 1.15 version of the mod has been released.

**Comment by deltaidea** [comment]
> 1.15 version of the mod has been released.

The latest file [on CurseForge](https://www.curseforge.com/minecraft/mc-mods/litematica/files) is named `litematica-fabric-1.14.4-0.0.0-dev.20191222.014040.jar` - is that the one? I think it's still named 1.14.4 by accident, or I'm not looking in the right place, is that the case? 🤔

**Comment by maruohon** [comment]
I want to merge in the latest code from 1.12 before I do the "official" 1.15.x release on CurseForge, as the current malilib version on 1.13.2/1.14.4/1.15.x is based on the June era code base, and for example has the annoying config reset bug when changing dimensions. But there are also still a bunch of other things I'd like to add to malilib before the release... but I think it would take me too long to do those as well before the release, so I should just do the merge soon and leave those new things for later.

**Comment by Andrews54757** [comment]
@maruohon I thought the issue was that the 1.15 version was based on a fork where you added a schematic importing feature. It seems to me that it is a bit more complicated than that, with the recent updates to the `master` (1.12) branch. It looks like the development of this mod been running in parallel rather than in sync with the 1.12 and 1.14-1.15 versions. Do you plan to merge their features across versions?

**Comment by maruohon** [comment]
Well yes the 1.15 port is currently on top of the `schematic-import` branch I have, but it's fairly straight forward to rebase it on the `fabric_1.14.4` branch instead. But I also want to merge the malilib changes from the 1.12/master branch asap to all the 1.13+ branches, because of the bug fixes and lots of improvements and additions.

All the main development happens in 1.12, and that code will occasionally get merged forward to 1.13.2 and then to 1.14.4 and now then also further to 1.15.1+. In the past few months I've in general done significantly less modding than before that, so development in general has slowed down a lot.

The two things that are not developed in 1.12 first, are the old schematic import support for which I have `schematic-import` branches in both 1.13.2 and 1.14.4. And the printer will most likely be added to the 1.14.4 branch first, as I don't plan to support that in 1.12 or 1.13.2, since the player base there is fairly small, mostly technical Minecraft players who generally don't like the printer anyway (like myself).
